using Eduard;
using Eduard.Security.Primitives;
using System.Diagnostics;

namespace Eduard.Security.Curves
{
    /// <summary>
    /// Implements arithmetic for Weierstrass elliptic curves using Jacobian-Chudnovsky <br/>
    /// coordinates (X, Y, Z, Z^2, Z^3) as described by Chudnovsky and Chudnovsky (1986).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Jacobian-Chudnovsky coordinates extend standard Jacobian representation by <br/>
    /// pre-computing Z^2 and Z^3. This optimization eliminates redundant squaring and <br/>
    /// cubing operations during mixed coordinate addition, particularly beneficial <br/>
    /// in window-based scalar multiplication methods.
    /// </para>
    /// <para>
    /// Based on: Chudnovsky, D.V., Chudnovsky, G.V. (1986). "Sequences of numbers <br/>
    /// generated by addition in formal groups and new primality and factorization tests". <br/>
    /// Advances in Mathematics, pp. 385-434.
    /// </para>
    /// <para>
    /// The affine point (x, y) maps to (X, Y, Z, Z^2, Z^3) where:
    /// <list type="bullet">
    /// <item><description>x = X / Z^2</description></item>
    /// <item><description>y = Y / Z^3</description></item>
    /// </list>
    /// </para>
    /// </remarks>
#if !USE_PROFILER
    [DebuggerStepThrough]
#endif
    public static class Wei5Math
    {
        /// <summary>
        /// Adds two Jacobian-Chudnovsky points on a Weierstrass curve.
        /// </summary>
        /// <param name="curve">The elliptic curve context.</param>
        /// <param name="left">First point.</param>
        /// <param name="right">Second point.</param>
        /// <returns>The sum in Jacobian-Chudnovsky coordinates.</returns>
        /// <remarks>
        /// Uses pre-computed Z^2 and Z^3 values to reduce field multiplications. <br/>
        /// Handles point at infinity cases and returns infinity when Z = 0.
        /// </remarks>
        public static ECPoint5w Add(EllipticCurve curve, ECPoint5w left, ECPoint5w right)
        {
            if (left == ECPoint5w.POINT_INFINITY) return right;
            if (right == ECPoint5w.POINT_INFINITY) return left;
            BigInteger p = curve.field;

            BigInteger A1 = (left.x * right.z2) % p;
            BigInteger A2 = (right.x * left.z2) % p;

            BigInteger A3 = (left.y * right.z3) % p;
            BigInteger A4 = (right.y * left.z3) % p;

            BigInteger A5 = A2 - A1;
            if (A5 < 0) A5 += p;

            BigInteger A6 = A4 - A3;
            if (A6 < 0) A6 += p;

            BigInteger A7 = (A5 * A5) % p;
            BigInteger A8 = (A5 * A7) % p;

            BigInteger A9 = (A1 * A7) % p;
            BigInteger X = (((A6 * A6) % p) - A8 - 2 * A9) % p;
            if (X < 0) X += p;

            BigInteger Y = (((A6 * (A9 - X)) % p) - A3 * A8) % p;
            if (Y < 0) Y += p;

            BigInteger Z = (((left.z * right.z) % p) * A5) % p;
            if (Z == 0) return ECPoint5w.POINT_INFINITY;
            BigInteger Z2 = (Z * Z) % p;

            BigInteger Z3 = (Z2 * Z) % p;
            return new ECPoint5w(X, Y, Z, Z2, Z3);
        }

        /// <summary>
        /// Doubles a Jacobian-Chudnovsky point on a Weierstrass curve.
        /// </summary>
        /// <param name="curve">The elliptic curve context.</param>
        /// <param name="jacobianPoint">The point to double.</param>
        /// <returns>The doubled point (2P) in Jacobian-Chudnovsky coordinates.</returns>
        /// <remarks>
        /// <para>
        /// Uses pre-computed Z^2 value to optimize doubling. For curves with a = -3, <br/>
        /// a specialized formula reduces multiplications by reusing Z^2 directly.
        /// </para>
        /// <para>
        /// Returns infinity when doubling a point of order 2 (Z = 0).
        /// </para>
        /// </remarks>
        public static ECPoint5w Doubling(EllipticCurve curve, ECPoint5w jacobianPoint)
        {
            if (jacobianPoint == ECPoint5w.POINT_INFINITY) return ECPoint5w.POINT_INFINITY;
            BigInteger p = curve.field;

            BigInteger A1 = (jacobianPoint.y * jacobianPoint.y) % p;
            BigInteger A2 = (4 * jacobianPoint.x * A1) % p;

            BigInteger A3 = (8 * A1 * A1) % p;
            BigInteger A4 = 0;

            if (curve.a != p - 3)
                A4 = ((3 * jacobianPoint.x * jacobianPoint.x) % p + (curve.a * ((jacobianPoint.z2 * jacobianPoint.z2) % p)) % p) % p;
            else
            {
                /* special case when Weierstrass curve parameter a = -3 */
                A4 = (3 * (jacobianPoint.x - jacobianPoint.z2) * (jacobianPoint.x + jacobianPoint.z2)) % p;
                if (A4 < 0) A4 += p;
            }

            BigInteger X = ((A4 * A4) % p - 2 * A2) % p;
            if (X < 0) X += p;

            BigInteger Y = (A4 * (A2 - X) - A3) % p;
            if (Y < 0) Y += p;

            BigInteger Z = (2 * jacobianPoint.y * jacobianPoint.z) % p;
            if (Z == 0) return ECPoint5w.POINT_INFINITY;
            BigInteger Z2 = (Z * Z) % p;

            BigInteger Z3 = (Z2 * Z) % p;
            return new ECPoint5w(X, Y, Z, Z2, Z3);
        }

        /// <summary>
        /// Computes the additive inverse of a Jacobian-Chudnovsky point.
        /// </summary>
        /// <param name="curve">The elliptic curve context.</param>
        /// <param name="point">The point to negate.</param>
        /// <returns>The point -P such that P + (-P) = point at infinity.</returns>
        /// <remarks>
        /// Negation flips the Y-coordinate: (X, Y, Z, Z^2, Z^3) -> (X, -Y, Z, Z^2, Z^3).<br/>
        /// The pre-computed Z^2 and Z^3 values remain unchanged.
        /// </remarks>
        public static ECPoint5w Negate(EllipticCurve curve, ECPoint5w point)
        {
            if (point == ECPoint5w.POINT_INFINITY) return ECPoint5w.POINT_INFINITY;
            return new ECPoint5w(point.x, curve.field - point.y, point.z, point.z2, point.z3);
        }
    }
}
