using Eduard;
using Eduard.Security.Primitives;
using System.Diagnostics;

namespace Eduard.Security.Curves
{
    /// <summary>
    /// Implements arithmetic for Weierstrass elliptic curves using Jacobian-Chudnovsky <br/>
    /// coordinates (X, Y, Z, Z^2, Z^3) as described by Chudnovsky and Chudnovsky (1986).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Jacobian-Chudnovsky coordinates extend standard Jacobian representation by <br/>
    /// pre-computing Z^2 and Z^3. This optimization eliminates redundant squaring and <br/>
    /// cubing operations during mixed coordinate addition, particularly beneficial <br/>
    /// in window-based scalar multiplication methods.
    /// </para>
    /// <para>
    /// Based on: Chudnovsky, D.V., Chudnovsky, G.V. (1986). "Sequences of numbers <br/>
    /// generated by addition in formal groups and new primality and factorization tests". <br/>
    /// Advances in Mathematics, pp. 385-434.
    /// </para>
    /// <para>
    /// The affine point (x, y) maps to (X, Y, Z, Z^2, Z^3) where:
    /// <list type="bullet">
    /// <item><description>x = X / Z^2</description></item>
    /// <item><description>y = Y / Z^3</description></item>
    /// </list>
    /// </para>
    /// </remarks>
#if !USE_PROFILER
    [DebuggerStepThrough]
#endif
    public static class Wei5Math
    {
        /// <summary>
        /// Adds two Jacobian-Chudnovsky points on a Weierstrass curve.
        /// </summary>
        /// <param name="curve">The elliptic curve context.</param>
        /// <param name="left">First point.</param>
        /// <param name="right">Second point.</param>
        /// <returns>The sum in Jacobian-Chudnovsky coordinates.</returns>
        /// <remarks>
        /// Uses pre-computed Z^2 and Z^3 values to reduce field multiplications. <br/>
        /// Handles point at infinity cases and returns infinity when Z = 0.
        /// </remarks>
        public static ECPoint5w Add(EllipticCurve curve, ECPoint5w left, ECPoint5w right)
        {
            if (left == ECPoint5w.POINT_INFINITY) return right;
            if (right == ECPoint5w.POINT_INFINITY) return left;
            BigInteger p = curve.field;

            BigInteger A1 = BarrettReducer.MulMod(left.x, right.z2);
            BigInteger A2 = BarrettReducer.MulMod(right.x, left.z2);

            BigInteger A3 = BarrettReducer.MulMod(left.y, right.z3);
            BigInteger A4 = BarrettReducer.MulMod(right.y, left.z3);

            BigInteger A5 = BarrettReducer.SubMod(A2, A1);
            BigInteger A6 = BarrettReducer.SubMod(A4, A3);

            BigInteger A7 = BarrettReducer.MulMod(A5, A5);
            BigInteger A8 = BarrettReducer.MulMod(A5, A7);

            BigInteger A9 = BarrettReducer.MulMod(A1, A7);
            BigInteger B1 = BarrettReducer.MulMod(A6, A6);

            BigInteger B2 = BarrettReducer.AddMod(A9, A9);
            BigInteger B3 = BarrettReducer.SubMod(B1, A8);

            BigInteger X = BarrettReducer.SubMod(B3, B2);
            BigInteger B4 = BarrettReducer.SubMod(A9, X);

            BigInteger B5 = BarrettReducer.MulMod(A6, B4);
            BigInteger B6 = BarrettReducer.MulMod(A3, A8);

            BigInteger Y = BarrettReducer.SubMod(B5, B6);
            BigInteger B7 = BarrettReducer.MulMod(left.z, right.z);

            BigInteger Z = BarrettReducer.MulMod(A5, B7);
            if (Z == 0) return ECPoint5w.POINT_INFINITY;
            BigInteger Z2 = BarrettReducer.MulMod(Z, Z);

            BigInteger Z3 = BarrettReducer.MulMod(Z2, Z);
            return new ECPoint5w(X, Y, Z, Z2, Z3);
        }

        /// <summary>
        /// Doubles a Jacobian-Chudnovsky point on a Weierstrass curve.
        /// </summary>
        /// <param name="curve">The elliptic curve context.</param>
        /// <param name="jacobianPoint">The point to double.</param>
        /// <returns>The doubled point (2P) in Jacobian-Chudnovsky coordinates.</returns>
        /// <remarks>
        /// <para>
        /// Uses pre-computed Z^2 value to optimize doubling. For curves with a = -3, <br/>
        /// a specialized formula reduces multiplications by reusing Z^2 directly.
        /// </para>
        /// <para>
        /// Returns infinity when doubling a point of order 2 (Z = 0).
        /// </para>
        /// </remarks>
        public static ECPoint5w Doubling(EllipticCurve curve, ECPoint5w jacobianPoint)
        {
            if (jacobianPoint == ECPoint5w.POINT_INFINITY) return ECPoint5w.POINT_INFINITY;
            BigInteger p = curve.field;

            BigInteger A1 = BarrettReducer.MulMod(jacobianPoint.y, jacobianPoint.y);
            BigInteger B1 = BarrettReducer.MulMod(jacobianPoint.x, A1);

            BigInteger A2 = BarrettReducer.MulMod(4, B1);
            BigInteger B2 = BarrettReducer.MulMod(A1, A1);

            BigInteger A3 = BarrettReducer.MulMod(8, B2);
            BigInteger A4 = 0;

            if (curve.a != p - 3)
            {
                BigInteger X12 = BarrettReducer.MulMod(jacobianPoint.x, jacobianPoint.x);
                BigInteger Z24 = BarrettReducer.MulMod(jacobianPoint.z2, jacobianPoint.z2);

                BigInteger B3 = BarrettReducer.MulMod(3, X12);
                BigInteger B4 = BarrettReducer.MulMod(curve.a, Z24);
                A4 = BarrettReducer.AddMod(B3, B4);
            }
            else
            {
                /* special case when Weierstrass curve parameter a = -3 */
                BigInteger B3 = BarrettReducer.SubMod(jacobianPoint.x, jacobianPoint.z2);
                BigInteger B4 = BarrettReducer.AddMod(jacobianPoint.x, jacobianPoint.z2);

                BigInteger A4t = BarrettReducer.MulMod(B3, B4);
                A4 = BarrettReducer.MulMod(3, A4t);
            }

            BigInteger B5 = BarrettReducer.MulMod(A4, A4);
            BigInteger B6 = BarrettReducer.AddMod(A2, A2);

            BigInteger X = BarrettReducer.SubMod(B5, B6);
            BigInteger B7 = BarrettReducer.SubMod(A2, X);

            BigInteger B8 = BarrettReducer.MulMod(A4, B7);
            BigInteger Y = BarrettReducer.SubMod(B8, A3);

            BigInteger B9 = BarrettReducer.MulMod(jacobianPoint.y, jacobianPoint.z);
            BigInteger Z = BarrettReducer.AddMod(B9, B9);

            if (Z == 0) return ECPoint5w.POINT_INFINITY;
            BigInteger Z2 = BarrettReducer.MulMod(Z, Z);

            BigInteger Z3 = BarrettReducer.MulMod(Z2, Z);
            return new ECPoint5w(X, Y, Z, Z2, Z3);
        }

        /// <summary>
        /// Computes the additive inverse of a Jacobian-Chudnovsky point.
        /// </summary>
        /// <param name="curve">The elliptic curve context.</param>
        /// <param name="point">The point to negate.</param>
        /// <returns>The point -P such that P + (-P) = point at infinity.</returns>
        /// <remarks>
        /// Negation flips the Y-coordinate: (X, Y, Z, Z^2, Z^3) -> (X, -Y, Z, Z^2, Z^3).<br/>
        /// The pre-computed Z^2 and Z^3 values remain unchanged.
        /// </remarks>
        public static ECPoint5w Negate(EllipticCurve curve, ECPoint5w point)
        {
            if (point == ECPoint5w.POINT_INFINITY) return ECPoint5w.POINT_INFINITY;
            return new ECPoint5w(point.x, curve.field - point.y, point.z, point.z2, point.z3);
        }
    }
}
