using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace Eduard
{
    /// <summary>
    /// Generates prime numbers up to a specified limit using the Sieve of Atkin, <br/>
    /// optimized for cryptographic parameter generation where prime lists are <br/>
    /// frequently needed for field and curve selection.
    /// </summary>
#if !USE_PROFILER
    [DebuggerStepThrough]
#endif
    public struct Sieve
    {
        /// <summary>
        /// Cached array of primes discovered during sieving.
        /// </summary>
        private int[] array;

        /// <summary>
        /// The total number of primes generated by the sieve.
        /// </summary>
        private int length;

        /// <summary>
        /// Initializes the sieve and generates all primes up to the specified limit.
        /// </summary>
        /// <param name="limit">The exclusive upper bound for prime generation.</param>
        /// <exception cref="ArgumentOutOfRangeException">Thrown when limit is less than 2.</exception>
        public Sieve(int limit)
        {
            if (limit < 2)
                throw new ArgumentOutOfRangeException(nameof(limit),
                    "Limit must be at least 2 to generate primes.");

            GenPrimeList(limit);
        }

        private void GenPrimeList(int limit)
        {
            var list = new List<int>();
            int root = (int)Math.Sqrt(limit) + 1;
            byte[] sieve = new byte[limit + 1];

            for (int x = 1; x < root; x++)
            {
                long x2 = (long)x * x;
                long x24 = x2 << 2;
                long x23 = x24 - x2;

                for (int y = 1; y < root; y++)
                {
                    long y2 = (long)y * y;
                    long k = x24 + y2;

                    if ((k < limit) && ((k % 12 == 1) || (k % 12 == 5)))
                        sieve[k] ^= 1;

                    k = x23 + y2;

                    if ((k < limit) && (k % 12 == 7))
                        sieve[k] ^= 1;

                    if (x > y)
                    {
                        k = x23 - y2;

                        if ((k < limit) && (k % 12 == 11))
                            sieve[k] ^= 1;
                    }
                }
            }

            if(limit >= 2) 
                sieve[2] = 1;

            if (limit >= 3) 
                sieve[3] = 1;

            for (int n = 5; n <= root; n++)
            {
                if (sieve[n] == 1)
                {
                    int square = n * n;

                    for (int t = square; t < limit; t += square)
                        sieve[t] = 0;
                }
            }

            list.Add(2);

            for (int k = 3; k <= limit; k += 2)
            {
                if (sieve[k] == 1)
                    list.Add(k);
            }

            array = list.ToArray();
            length = array.Length;
        }

        /// <summary>
        /// Retrieves the prime at the specified zero-based index.
        /// </summary>
        /// <param name="index">The zero-based index of the prime to retrieve.</param>
        /// <returns>The prime number at the specified index.</returns>
        /// <exception cref="ArgumentOutOfRangeException">
        /// Thrown when index is negative or exceeds the number of primes generated.
        /// </exception>
        public int this[int index]
        {
            get
            {
                if (index < 0 || index >= length)
                    throw new ArgumentOutOfRangeException(nameof(index),
                        "Index must be non-negative and less than the " 
                        + "total prime count.");

                return array[index];
            }
        }

        /// <summary>
        /// The total number of primes generated by the sieve.
        /// </summary>
        public int Count
        { get { return length; } }
    }
}